package:
  name: homebridge
  version: 1.11.4
  epoch: 0
  description: "homebridge is a lightweight Node.js server that emulates the iOS HomeKit API"

  dependencies:
    runtime:
      - nodejs-24
    
environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - nodejs-24
      - npm

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/homebridge/homebridge
      tag: v${{package.version}}
      expected-commit: 7df9f1bfe577615a31e6baa2542ddc3a72f2e07f

  - name: npm test
    runs: |
      set -x
      npm install
      npm test

  - name: npm install 
    runs: |
      npm install -g ${{package.name}}@${{package.version}} -prefix ${{targets.destdir}}/usr
      chmod -R a+r ${{targets.destdir}}/usr/lib/node_modules
      find ${{targets.destdir}}/usr/lib/node_modules -type d -exec chmod a+x {} \; 
            
test:
  environment:
    contents:
      keyring:
        - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      repositories:
        - https://packages.wolfi.dev/os
      packages:
        - wolfi-base
        - nodejs-24
        - homebridge
  pipeline:
    - name: Verify homebridge installation
      runs: |
        set -x
        node /usr/bin/homebridge --version

    - name: Verify permissions of }/usr/lib/node_modules are all readable/executable
      runs: |
        set -x
        found=$(find /usr/lib/node_modules ! -perm -a=r -print -quit)
        if [ -n "$found" ]; then
          echo "File with incorrect permissions found: $found"
          ls -l "$found"
          exit 1
        fi
        found=$(find /usr/lib/node_modules -type d ! -perm -a=x -print -quit)
        if [ -n "$found" ]; then
          echo "Directory with incorrect permissions found: $found"
          ls -ld "$found"
          exit 1
        fi
